## Engineering Dates

Date variables are special type of categorical variable. By their own nature, date variables will contain a multitude of different labels, each one corresponding to a specific date and sometimes time. Date variables, when preprocessed properly can highly enrich a dataset. For example, from a date variable we can extract:

- Week of the year
- Month
- Quarter
- Semester
- Year
- Day (number)
- Day of the week
- Is Weekend?
- Time differences in years, months, days, hrs, etc.

Date variables should not be used as categorical variables when building a machine learning model. Not only because they have a multitude of categories, but also because when we actually use the model to score a new observation, this observation will most likely be in the future, an therefore its date label, might be different from the ones contained in the training set and therefore the ones used to train the machine learning algorithm.


## In this demo: Peer to peer lending (Finance)

In this demo, we will use data from the peer-o-peer finance company **Lending Club** to extract different features from datetime variables.

- To download the dataset, please refer to the **Datasets** lecture in **Section 1** of the course.

In [1]:
import pandas as pd
import numpy as np

import datetime

In [2]:
# let's load the Lending Club dataset with a few selected columns
# and just a few rows to speed things up

use_cols = ['issue_d', 'last_pymnt_d']
data = pd.read_csv('loan.csv', usecols=use_cols, nrows=10000)

data.head()

issue_d last_pymnt_d
0  Dec-2018     Feb-2019
1  Dec-2018     Feb-2019
2  Dec-2018     Feb-2019
3  Dec-2018     Feb-2019
4  Dec-2018     Feb-2019

In [3]:
# now let's parse the dates, currently cast as strings, into datetime format

data['issue_dt'] = pd.to_datetime(data.issue_d)
data['last_pymnt_dt'] = pd.to_datetime(data.last_pymnt_d)

data[['issue_d','issue_dt','last_pymnt_d', 'last_pymnt_dt']].head()

issue_d   issue_dt last_pymnt_d last_pymnt_dt
0  Dec-2018 2018-12-01     Feb-2019    2019-02-01
1  Dec-2018 2018-12-01     Feb-2019    2019-02-01
2  Dec-2018 2018-12-01     Feb-2019    2019-02-01
3  Dec-2018 2018-12-01     Feb-2019    2019-02-01
4  Dec-2018 2018-12-01     Feb-2019    2019-02-01

### Extract week of the year

In [4]:
# Extracting week of year from date, varies from 1 to 52

data['issue_dt_week'] = data['issue_dt'].dt.week

data[['issue_dt', 'issue_dt_week']].head()

issue_dt  issue_dt_week
0 2018-12-01             48
1 2018-12-01             48
2 2018-12-01             48
3 2018-12-01             48
4 2018-12-01             48

In [6]:
data['issue_dt_week'].unique()

array([48, 44, 39, 35, 31], dtype=int64)

### Extract month

In [5]:
# Extracting month from date - 1 to 12

data['issue_dt_month'] = data['issue_dt'].dt.month

data[['issue_dt', 'issue_dt_month']].head()

issue_dt  issue_dt_month
0 2018-12-01              12
1 2018-12-01              12
2 2018-12-01              12
3 2018-12-01              12
4 2018-12-01              12

In [6]:
data['issue_dt_month'].unique()

array([12], dtype=int64)

### Extract quarter

In [7]:
# Extract quarter from date variable - 1 to 4

data['issue_dt_quarter'] = data['issue_dt'].dt.quarter

data[['issue_dt', 'issue_dt_quarter']].head()

issue_dt  issue_dt_quarter
0 2018-12-01                 4
1 2018-12-01                 4
2 2018-12-01                 4
3 2018-12-01                 4
4 2018-12-01                 4

In [8]:
data['issue_dt_quarter'].unique()

array([4], dtype=int64)

### Extract semester

In [9]:
# We could also extract semester

data['issue_dt_semester'] = np.where(data['issue_dt_quarter'].isin([1,2]), 1, 2)

data.head()

issue_d last_pymnt_d   issue_dt last_pymnt_dt  issue_dt_week  \
0  Dec-2018     Feb-2019 2018-12-01    2019-02-01             48   
1  Dec-2018     Feb-2019 2018-12-01    2019-02-01             48   
2  Dec-2018     Feb-2019 2018-12-01    2019-02-01             48   
3  Dec-2018     Feb-2019 2018-12-01    2019-02-01             48   
4  Dec-2018     Feb-2019 2018-12-01    2019-02-01             48   

   issue_dt_month  issue_dt_quarter  issue_dt_semester  
0              12                 4                  2  
1              12                 4                  2  
2              12                 4                  2  
3              12                 4                  2  
4              12                 4                  2

In [10]:
data['issue_dt_semester'].unique()

array([2], dtype=int64)

###  Extract year

In [11]:
# extract year 

data['issue_dt_year'] = data['issue_dt'].dt.year

data[['issue_dt', 'issue_dt_year']].head()

issue_dt  issue_dt_year
0 2018-12-01           2018
1 2018-12-01           2018
2 2018-12-01           2018
3 2018-12-01           2018
4 2018-12-01           2018

In [12]:
data['issue_dt_year'].unique()

array([2018], dtype=int64)

### Extract days, in various formats

In [13]:
# day - numeric from 1-31

data['issue_dt_day'] = data['issue_dt'].dt.day

data[['issue_dt', 'issue_dt_day']].head()

issue_dt  issue_dt_day
0 2018-12-01             1
1 2018-12-01             1
2 2018-12-01             1
3 2018-12-01             1
4 2018-12-01             1

In [14]:
data['issue_dt_day'].unique()

array([1], dtype=int64)

In [15]:
# day of the week - from 0 to 6

data['issue_dt_dayofweek'] = data['issue_dt'].dt.dayofweek

data[['issue_dt', 'issue_dt_dayofweek']].head()

issue_dt  issue_dt_dayofweek
0 2018-12-01                   5
1 2018-12-01                   5
2 2018-12-01                   5
3 2018-12-01                   5
4 2018-12-01                   5

In [16]:
data['issue_dt_dayofweek'].unique()

array([5], dtype=int64)

In [17]:
# day of the week - name

data['issue_dt_dayofweek'] = data['issue_dt'].dt.weekday_name

data[['issue_dt', 'issue_dt_dayofweek']].head()

issue_dt issue_dt_dayofweek
0 2018-12-01           Saturday
1 2018-12-01           Saturday
2 2018-12-01           Saturday
3 2018-12-01           Saturday
4 2018-12-01           Saturday

In [18]:
data['issue_dt_dayofweek'].unique()

array(['Saturday'], dtype=object)

In [20]:
# was the application done on the weekend?

data['issue_dt_is_weekend'] = np.where(data['issue_dt_dayofweek'].isin(['Sunday', 'Saturday']), 1,0)

data[['issue_dt', 'issue_dt_dayofweek','issue_dt_is_weekend']].head()

issue_dt issue_dt_dayofweek  issue_dt_is_weekend
0 2018-12-01           Saturday                    1
1 2018-12-01           Saturday                    1
2 2018-12-01           Saturday                    1
3 2018-12-01           Saturday                    1
4 2018-12-01           Saturday                    1

In [21]:
data['issue_dt_is_weekend'].unique()

array([1], dtype=int64)

### Extract Time elapsed between dates

In [22]:
# perhaps more interestingly, extract the date difference between 2 dates

data['issue_dt'] - data['last_pymnt_dt']

0      -62 days
1      -62 days
2      -62 days
3      -62 days
4      -62 days
         ...   
9995   -62 days
9996   -62 days
9997   -62 days
9998   -62 days
9999   -62 days
Length: 10000, dtype: timedelta64[ns]

In [23]:
# same as above capturing just the time difference

(data['last_pymnt_dt'] - data['issue_dt']).dt.days.head()

0    62.0
1    62.0
2    62.0
3    62.0
4    62.0
dtype: float64

In [26]:
# calculate number of months passed between 2 dates

data['months_passed'] = (data['last_pymnt_dt'] - data['issue_dt']) / np.timedelta64(1, 'M')
data['months_passed'] = np.round(data['months_passed'],0)

data[['last_pymnt_dt', 'issue_dt','months_passed']].head()

last_pymnt_dt   issue_dt  months_passed
0    2019-02-01 2018-12-01            2.0
1    2019-02-01 2018-12-01            2.0
2    2019-02-01 2018-12-01            2.0
3    2019-02-01 2018-12-01            2.0
4    2019-02-01 2018-12-01            2.0

In [27]:
# or the time difference to today

(datetime.datetime.today() - data['issue_dt']).head()

0   456 days 21:49:45.766215
1   456 days 21:49:45.766215
2   456 days 21:49:45.766215
3   456 days 21:49:45.766215
4   456 days 21:49:45.766215
Name: issue_dt, dtype: timedelta64[ns]

In [29]:
(datetime.datetime.today() - data['issue_dt']).unique()

array([39477003802330000], dtype='timedelta64[ns]')